### ISSUE TITLE
Sometimes the redstone is not cleared from the players inventory after closing a session

### ISSUE THREAD

**Issue by SeqSEE** [Josewowgame2888/TrackSystem#1]
After closing a session sometimes the redstone is not cleared from the player's inventory other times the entire inventory is cleared from the player.

 **I would recommend the following steps in this order:**

1. Store a copy of the player's gamemode, inventory and location at the time of the command in memory or on disk (or both).
2. Clear the inventory and add the special item. 
3. Put the player in the session. 
**On player exit session schedule a task to:**
1. Clear the inventory and add back the stored copy of the inventory. 
2. Teleport the player back to where they were and set the gamemode back to what it was.

**Comment by Josewowgame2888** [comment]
I will implement it in the next update
